### ISSUE TITLE
Checkpoint #1 Doesn't Work

### ISSUE THREAD

**Issue by soynog** [ga-wdi-boston/js-modules-study#17]
Putting parens around the function declaration breaks the script, at least for me.

``` js
(function f(initialValue) {
  // declare some variables in here that will be hidden from outside
  let a = initialValue;

  // `g` will have access to variables in this scope, such as `a`
  function g() {
    return Math.floor(Math.random() * a);
  }

  // return the function so we can access it from outside
  return g;
});
```

**Comment by RealWeeks** [comment]
This may have been a 1 off issue because I don't remember anyone else having it but I'm going to keep open to document.

**Comment by gaand** [comment]
Wrapping a function declaration in parens converts it to a function expression, so it is no longer created in the global scope.

Found by @jordanallain 25/08/2016T20:43

**Comment by gaand** [comment]
@ga-wdi-boston/core We should be more careful with issues opened on studies (as they're work the developers do on their own).  It took me less than a minute to confirm this behavior.

**Comment by gaand** [comment]
ga-wdi-boston/js-modules-study/pull/44

**Comment by rhjones** [comment]
Resurfacing this—the instructions haven't changed, and following them exactly produces a Reference Error when you try to rerun the script because `f` is no longer defined globally.

**Comment by tuckyeah** [comment]
yep, I got the same thing!

Also, Checkpoint 1 tells us to run "index.js" instead of "inline.js," which also produces an error since there is nothing in index.js

**Comment by neugierige** [comment]
this issue has been sufficiently addressed
